services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    restart: always
    depends_on:
     - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
      - ./plugins/${PLUGIN_SLUG}:/var/www/html/wp-content/plugins/${PLUGIN_SLUG}:ro #Run over environment variable
      - ./plugins/benchmark-log-plugin:/var/www/html/wp-content/plugins/benchmark-log-plugin:ro
      - ./plugins/test.php:/var/www/html/wp-content/plugins/test.php:ro
      - ./plugins/function-hooking-plugin:/var/www/html/wp-content/plugins/function-hooking-plugin:ro
  
  wordpress-cli: #Needed for automatic interaction
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: '33' # For permissions
    command: ['sh', '/seed-script.sh']
    volumes: #Same as wp instance
    - wordpress:/var/www/html
    - ./plugins/${PLUGIN_SLUG}:/var/www/html/wp-content/plugins/${PLUGIN_SLUG}:ro
    - ./plugins/benchmark-log-plugin:/var/www/html/wp-content/plugins/benchmark-log-plugin:ro
    - ./plugins/test.php:/var/www/html/wp-content/plugins/test.php:ro
    - ./plugins/function-hooking-plugin:/var/www/html/wp-content/plugins/function-hooking-plugin:ro
    - ./seed-script.sh:/seed-script.sh:ro
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      PLUGIN_SLUG: ${PLUGIN_SLUG}


  #runner:
  #Container to trigger AJAX/REST dynamic Analysis

  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    volumes:
      - wordpress:/var/www/html:ro

  #Container to look out for file changes
volumes:
  wordpress:
  db:


  #Freshly seeded MariaDB/MySQL
  
